# Generated by Django 4.2.16 on 2026-07-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceCodeName', models.CharField(max_length=20, unique=True)),
                ('DisplayLabel', models.CharField(max_length=50)),
                ('SortOrder', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='price_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PriceCodeList_tbl',
                'ordering': ['SortOrder', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProductGroup_tbl',
                'ordering': ['GroupName'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(editable=False, max_length=50, unique=True)),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductNameTamil', models.CharField(blank=True, max_length=200, null=True)),
                ('HSNCode', models.CharField(blank=True, max_length=20, null=True)),
                ('GSTPercent', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Units', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('GroupId', models.ForeignKey(blank=True, db_column='GroupId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productgroup')),
            ],
            options={
                'db_table': 'Product_tbl',
                'ordering': ['-CreatedOn'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceName', models.CharField(choices=[('A', 'Price A'), ('B', 'Price B'), ('C', 'Price C'), ('D', 'Price D'), ('Retail', 'Retail Price')], default='Retail', max_length=20)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to=settings.AUTH_USER_MODEL)),
                ('PriceCodeID', models.ForeignKey(db_column='PriceCodeID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='products.pricecodelist')),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'db_table': 'Product_Price_Details_tbl',
                'ordering': ['ProductId', 'PriceName'],
                'indexes': [models.Index(fields=['ProductId'], name='idx_price_product')],
                'unique_together': {('ProductId', 'PriceCodeID')},
            },
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['GroupName'], name='idx_group_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductName'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['CreatedOn'], name='idx_product_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['GroupId'], name='idx_product_group'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductCode'], name='idx_product_code'),
        ),
    ]
