# Generated by Django 4.2.16 on 2026-07-13 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=200, unique=True)),
                ('UQC', models.CharField(blank=True, max_length=50, null=True)),
                ('Decimal', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Unit_tbl',
                'ordering': ['UnitName'],
            },
        ),
    ]
