# Generated by Django 4.2.16 on 2026-07-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('keyboard_shortcuts_enabled', models.BooleanField(default=True)),
                ('keyboard_shortcuts', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'db_table': 'User_Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'Notification_tbl',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('HasGST', models.BooleanField(default=False)),
                ('IsGSTEnabled', models.BooleanField(default=False)),
                ('GSTNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('GSTNo', models.CharField(blank=True, max_length=15, null=True)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='company_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Information (Legacy)',
                'db_table': 'Company_Info',
            },
        ),
        migrations.CreateModel(
            name='CompanyConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.TextField()),
                ('IsGSTRegistered', models.BooleanField(default=False)),
                ('GSTNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('CompanyLogo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('ChangedOn', models.DateTimeField(auto_now_add=True)),
                ('ChangedBy', models.ForeignKey(db_column='ChangedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_config_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Config History',
                'db_table': 'CompanyInfo_History_tbl',
                'ordering': ['-ChangedOn'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyCode', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('CompanyName', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.TextField()),
                ('IsGSTRegistered', models.BooleanField(default=False)),
                ('GSTNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('CompanyLogo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='company_config_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'db_table': 'CompanyInfo_tbl',
            },
        ),
    ]
