# Generated by Django 4.2.16 on 2026-07-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyconfighistory',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
