# Generated by Django 4.2.16 on 2026-07-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillNo', models.CharField(max_length=50, unique=True)),
                ('BillDate', models.DateTimeField(auto_now_add=True)),
                ('PriceCodeType', models.CharField(max_length=10)),
                ('IsGSTBill', models.BooleanField(default=False)),
                ('ItemCount', models.IntegerField(default=0)),
                ('SubTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('TotalDiscount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('GSTAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('TotalCGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('TotalSGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('TotalIGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('GrandTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('EarnedPoints', models.IntegerField(default=0)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to=settings.AUTH_USER_MODEL)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='customers.customer')),
                ('DefaultPriceCodeID', models.ForeignKey(blank=True, db_column='DefaultPriceCodeID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='products.pricecodelist')),
            ],
            options={
                'db_table': 'BillingHeader_tbl',
                'ordering': ['-CreatedOn'],
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNo', models.IntegerField(default=1)),
                ('Qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsDiscountApplied', models.BooleanField(default=False)),
                ('DiscountPercent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('IsGSTApplied', models.BooleanField(default=False)),
                ('GSTPercent', models.IntegerField(default=0)),
                ('GSTAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('CGSTAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('SGSTAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('IGSTAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('GSTType', models.CharField(choices=[('NONE', 'No GST'), ('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='NONE', max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('EarnedPoints', models.IntegerField(default=0)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('BillingHeaderID', models.ForeignKey(db_column='BillingHeaderID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.billingheader')),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='billings', to=settings.AUTH_USER_MODEL)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='customers.customer')),
                ('PriceCodeID', models.ForeignKey(db_column='PriceCodeID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='products.pricecodelist')),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='products.product')),
            ],
            options={
                'db_table': 'Billing_tbl',
                'ordering': ['-CreatedOn'],
            },
        ),
        migrations.AddIndex(
            model_name='billingheader',
            index=models.Index(fields=['BillNo'], name='idx_bill_no'),
        ),
        migrations.AddIndex(
            model_name='billingheader',
            index=models.Index(fields=['CustomerID'], name='idx_billhdr_customer'),
        ),
        migrations.AddIndex(
            model_name='billingheader',
            index=models.Index(fields=['CreatedOn'], name='idx_billhdr_created'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['CustomerID'], name='idx_billing_customer'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['ProductID'], name='idx_billing_product'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['CreatedOn'], name='idx_billing_created'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['BillingHeaderID', 'LineNo'], name='idx_billing_header_line'),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('BillingHeaderID', 'LineNo')},
        ),
    ]
