# Generated by Django 4.2.16 on 2026-07-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='ChangeableRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowDiscount', models.BooleanField(default=False)),
                ('SkipEnabled', models.BooleanField(default=False)),
                ('SkippedColumns', models.JSONField(blank=True, default=list)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UpdatedBy', models.ForeignKey(blank=True, db_column='UpdatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Configuration',
                'db_table': 'BillingConfig_tbl',
            },
        ),
    ]
