# Generated by Django 4.2.16 on 2026-07-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodegenerator', '0002_manual_price_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='barcodegenerator',
            name='idx_barcode_price',
        ),
    ]
