# Generated by Django 4.2.16 on 2026-07-17 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Revoked_Refresh_Token_tbl',
                'ordering': ['-revoked_at'],
                'indexes': [models.Index(fields=['jti'], name='idx_revoked_refresh_jti'), models.Index(fields=['expires_at'], name='idx_revoked_refresh_exp'), models.Index(fields=['user', 'expires_at'], name='idx_revoked_refresh_user_exp')],
            },
        ),
    ]
