# Generated by Django 4.2.16 on 2026-07-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerCode', models.CharField(editable=False, max_length=50, unique=True)),
                ('CustomerName', models.CharField(max_length=200)),
                ('Address', models.TextField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('WhatsappNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('IsWhatsappSameAsPhone', models.BooleanField(default=False)),
                ('EmailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('IsGSTCustomer', models.BooleanField(default=False)),
                ('GSTNo', models.CharField(blank=True, max_length=20, null=True)),
                ('PriceCode', models.CharField(default='Retail', max_length=100)),
                ('PriceCodeType', models.CharField(choices=[('Fixed', 'Fixed Price'), ('Random', 'Random Price')], default='Fixed', max_length=10)),
                ('Customer_Redeem_Points', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer_tbl',
                'ordering': ['-CreatedOn'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceCodeType', models.CharField(choices=[('Fixed', 'Fixed Price'), ('Random', 'Random Price')], max_length=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.PROTECT, related_name='customer_price_configs', to=settings.AUTH_USER_MODEL)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='price_configs', to='customers.customer')),
                ('FixedPriceCodeID', models.ForeignKey(blank=True, db_column='FixedPriceCodeID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_configs', to='products.pricecodelist')),
            ],
            options={
                'db_table': 'CustomerPriceConfig_tbl',
                'ordering': ['-CreatedOn'],
                'indexes': [models.Index(fields=['CustomerID', 'IsActive'], name='idx_cust_price_active')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['CustomerCode'], name='idx_customer_code'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['CustomerName'], name='idx_customer_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['PhoneNumber'], name='idx_customer_phone'),
        ),
    ]
